channels:
  - conda-forge

dependencies:
  # For building the lessons website
  - 'git>=2.28'
  - 'r-base>=3.6'
  - 'pandoc>=2.11'
  - pkg-config
  - libxslt
  - r-httr2
  - r-pkgdown
  - r-httpuv
  - r-servr
  # For testing the lessons
  - python
  - scons
  - numpy
  - matplotlib
