import os
import pathlib

from SCons.Node.Alias import default_ans
from SCons.Script import DEFAULT_TARGETS

from scons_lesson_configuration import *

AddOption(
    "--variables",
    action="store_true",
    default=False,
    help="Print the files returned by Glob and exit (default: '%default')",
)
if GetOption("variables"):
    text_file_strings = [str(node) for node in TEXT_FILES]
    print(f"TEXT_FILES: {text_file_strings}")
    print(f"DATA_FILES: {DATA_FILES}")
    Exit(0)

env = Environment(ENV=os.environ.copy())
env.AddMethod(count_words, "CountWords")
env.CountWords(DATA_FILES)
env.Alias("dats", DATA_FILES)

env.Command(
    target=["results.txt"],
    source=[ZIPF_SOURCE] + DATA_FILES,
    action=["${language} ${zipf_source} ${SOURCES[1:]} > ${TARGET}"],
    language=LANGUAGE,
    zipf_source=ZIPF_SOURCE,
)

env.Default(["results.txt"])

help_message = "\nDefault Targets:\n"
for target in DEFAULT_TARGETS:
    help_message += f"    {str(target)}\n"
help_message += "\nTarget Aliases:\n"
for alias in default_ans:
    help_message += f"    {alias}\n"
env.Help(help_message, append=True, keep_local=True)
